version: '2'
services:
  kafka:
    image: confluent/kafka:0.9.0.0-cp1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.80.80.80
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    # volumes:
    #   - ./venv/kafka/data:/var/lib/kafka/data
    links:
      - zookeeper
    depends_on:
      - zookeeper


  zookeeper:
    image: confluent/zookeeper
    ports:
        - "2181:2181"
